### ISSUE TITLE
It times out because they've started using captcha images

### ISSUE THREAD

**Issue by yidohaile** [sepiropht/frontend-master-downloader#12]
It is unable to login because they've started using captcha images. Can you fix this?

**Comment by sepiropht** [comment]
Sadly i have no solutions for that. But i can update the script to set the headless mode to false and so you can resolve the captcha yourself. Of course it become mandatory to increase the timeout so the human user will have time to resolve all the captchas. 
After that i hope the script can can continue like usual.
An other solution much more fun is to learn deep learning to resolve captcha !  I will try to explore that but i really doubt that i can win there, it is really difficult subject. 
Unfortunately there is not such course in frontend-master ha ha.

**Comment by yidohaile** [comment]
I completely understand so I was wondering if we can get a solution as follows:

**Comment by sepiropht** [comment]
The first one is easy. I can save all links in in json format in a file.
The second might be possible but for now i don't see clear way to achieve that.

**Comment by sepiropht** [comment]
You can use [this one](https://github.com/li-xinyang/OS_FrontendMaster-dl)
i don't know why, but it seems that it isn't affected by captcha.

**Comment by sepiropht** [comment]
I  will close this, i don't know why but they removed captcha

**Comment by tamirbenCA** [comment]
It doesn't work again.
A few weeks ago it started working again, but i tried to downloaded today some new courses and it timed out again.
