### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: waiting failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by abhishekneu** [sepiropht/frontend-master-downloader#13]
I am using frontend-master-downloader v 1.1.1 and getting below error 
```
➜  FE_courses frontend-master-downloader -u Goku -p ********* -c complete-react-v4
You are using frontendmaster-downloader

Try the login ...

Goku logged

First scrape all the links...

(node:27336) UnhandledPromiseRejectionWarning: Error: waiting failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (/usr/local/lib/node_modules/frontend-master-downloader/node_modules/puppeteer/lib/FrameManager.js:593:58)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
(node:27336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by chasen-bettinger** [comment]
I tried to debug it because I received the same error by cloning the project but it works on my own machine. I'll see if I can get to the bottom of it.

**Comment by nimaa77** [comment]
same here

**Comment by nimaa77** [comment]
changing user-agent in [crawler.js](https://github.com/sepiropht/frontend-master-downloader/blob/master/crawler.js#L14) fixed problem for me

**Comment by ThinkSalat** [comment]
> changing user-agent in [crawler.js](https://github.com/sepiropht/frontend-master-downloader/blob/master/crawler.js#L14) fixed problem for me

@nimaa77 What did you change it to?

**Comment by nimaa77** [comment]
> > changing user-agent in [crawler.js](https://github.com/sepiropht/frontend-master-downloader/blob/master/crawler.js#L14) fixed problem for me
> 
> @nimaa77 What did you change it to?

just open your browser developer console in some random page (even this github page) and type
`navigator.userAgent`

and next thing i have to mention is IF YOU ENTER WRONG USERNAME and PASSWORD you well get this error message as well

tell me if it works for you 3>

**Comment by ThinkSalat** [comment]
> > > changing user-agent in [crawler.js](https://github.com/sepiropht/frontend-master-downloader/blob/master/crawler.js#L14) fixed problem for me
> > 
> > 
> > @nimaa77 What did you change it to?
> 
> just open your browser developer console in some random page (even this github page) and type
> `navigator.userAgent`
> 
> and next thing i have to mention is IF YOU ENTER WRONG USERNAME and PASSWORD you well get this error message as well
> 
> tell me if it works for you 3>

I got it working! It was actually my credentials.

**Comment by evanzummeren** [comment]
Having similar issues. The problem is actually that the script is stuck at the recaptcha. Changing the user agent could solve it, but in my case it doesn't. The [Python-script](https://github.com/li-xinyang/OS_FrontendMaster-dl) has the same problem...
