### ISSUE TITLE
You have reached maximum request limit

### ISSUE THREAD

**Issue by stella02** [sepiropht/frontend-master-downloader#18]

**Comment by stella02** [comment]
Have download 2 courses, below error was observed " you have reached maximum reuqest limit".

After waiting for hours, I increase the gap between each request, but seems that this error would show after scraping http://....  for 17 times. 
Is there any solution? ie download video one by one?
Thanks in advance !

**Comment by gromen** [comment]
I have similar issue after command `$ sudo frontend-master-downloader -u username -p password -c graphql`

![screenshot from 2019-02-11 12-35-47](https://user-images.githubusercontent.com/14578910/52561912-0aa3e600-2dfd-11e9-8d1a-2af9c1a43dba.png)

OS - Ubuntu 18.04
Browser - Chrome v72.0.3626.96 
chromedriver - https://chromedriver.storage.googleapis.com/index.html?path=2.46/

Any solution ?
