### ISSUE TITLE
Unhandled promise rejection 

### ISSUE THREAD

**Issue by eldyvoon** [sepiropht/frontend-master-downloader#3]
frontend-master-downloader -u username -p pass -c javascript-foundations

able to download a course but for my second attempt I got this error `
(node:7004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Page.navigate): Invalid parameters url: string value expected`

**Comment by eldyvoon** [comment]
@stalwart201 some course it's working fine, I skipped javascript-foundations.

**Comment by sepiropht** [comment]
I downloaded javascript-foundations without problems, this problems it's odd.
I will look at it.

**Comment by stalwart201** [comment]
thank you so much @sepiropht. I will also try to figure out meanwhile.

**Comment by sepiropht** [comment]
I just downloaded 3 courses right now : testing-react, graphQl-node-api and javascript-fondations. And i faced absolutely no problem at all. I have all the files for the tree courses.

What versions of the script do use ? Try frontend-master-downloader -v and it should return 1.1.0
