### ISSUE TITLE
(node:83426) UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by xiaofanr** [sepiropht/frontend-master-downloader#6]
> (node:83426) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/usr/local/lib/node_modules/frontend-master-downloader/node_modules/puppeteer/lib/NavigatorWatcher.js:69:21)

> (node:83426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

> (node:83426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

No video is downloaded
macOS 10.14.4
Node v10.5.0

**Comment by Globerada** [comment]
(node:7356) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Page.navigate): Invalid parameters url: string value expected
(node:7356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


Same here with Windows 10. 
chromedriver is already in path.

**Comment by bala1074** [comment]
Try the login ... 

(node:1136) UnhandledPromiseRejectionWarning: TypeError: text is not iterable
    at Keyboard.type (/Users/bala_in/.nvm/versions/node/v9.9.0/lib/node_modules/frontend-master-downloader/node_modules/puppeteer/lib/Input.js:168:24)
    at ElementHandle.type (/Users/bala_in/.nvm/versions/node/v9.9.0/lib/node_modules/frontend-master-downloader/node_modules/puppeteer/lib/ElementHandle.js:108:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:1136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:1136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Mac

**Comment by hreyVS** [comment]
You are using frontendmaster-downloader 

Try the login ... 

hlrd_93@hotmail.com logged 

First scrape all the links... 

(node:28841) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: waiting failed: timeout 30000ms exceeded
(node:28841) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by XHMM** [comment]
try add these args
`const browser = await puppeteer.launch({
args: ["--proxy-server='direct://'", '--proxy-bypass-list=*']
})`
